version: "3"
services:
  pintos_mesa_h:
    image: tomcat:8
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: pin_mesa_h
    ports:
      - "8012:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
      LANG: 'pt_BR.UTF-8'
      LANGUAGE: 'pt_BR:pt'
      LC_ALL: 'pt_BR.UTF-8'
    volumes:
      - ./build/libs/homologacao.war:/usr/local/tomcat/webapps/mesaCredito.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_mesa_h:
        ipv4_address: 172.113.1.1
networks:
  rede_mesa_h:
    ipam:
      driver: default
      config:
        - subnet: 172.113.0.0/16

