version: "3"
services:
  pintos_mesa:
    image: tomcat:8
    container_name: pin_mesa
    ports:
      - "8011:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
      LANG: 'pt_BR.UTF-8'
      LANGUAGE: 'pt_BR:pt'
      LC_ALL: 'pt_BR.UTF-8'
    volumes:
      - ./build/libs/producao.war:/usr/local/tomcat/webapps/mesaCredito.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_mesa:
        ipv4_address: 172.111.1.1
networks:
  rede_mesa:
    ipam:
      driver: default
      config:
        - subnet: 172.111.0.0/16
